#!/bin/bash
#MISE description="checkout git branch (including remote branches)"
#MISE dir="{{cwd}}"

branches=$(git branch --all | grep -v HEAD)
branch=$(echo "$branches" | fzf --height 40% --reverse +m)
if [ -n "$branch" ]; then
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
fi
