prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
  - title: Needs My Review
    filters: is:open review-requested:@me
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: false # wether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths: # configure where to locate repos when checking out PRs
  dlvhdr/*: ~/code/repos/* # will match dlvhdr/repo-name to ~/code/repos/repo-name
  dlvhdr/gh-dash: ~/code/gh-dash # will not match wildcard and map to specified path
keybindings: # optional, define custom keybindings - see more info below
theme: # optional, see more info below
  colors:
    background:
      selected: "#81A1C1"
    border:
      faint:     "#3B4252"
      primary:   "#4C566A"
      secondary: "#434C5E"
    text:
      faint:     "#4C566A"
      inverted:  "#D8DEE9"
      primary:   "#FFFFFF"
      secondary: "#81A1C1"
      success:   "#A3BE8C"
      warning:   "#EBCB8B"
  ui:
    table:
      showSeparators: true
pager:
  diff: "delta" # or delta for example
